version: "2"
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - nolintlint
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
formatters:
  enable:
    - gofmt
    - goimports
